export const constants = {
    // Products action types
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

    // Product Detail action types
    SINGLE_PRODUCT_REQUEST: 'SINGLE_PRODUCT_REQUEST',
    SINGLE_PRODUCT_SUCCESS: 'SINGLE_PRODUCT_SUCCESS',
    SINGLE_PRODUCT_FAILED: 'SINGLE_PRODUCT_FAILED',

    // Cart action types
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',

    // User action types (Register, Login, Update Profile)
    /* REGISTER */
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',

    /* LOGIN */
    USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST ',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    USER_LOGOUT: 'USER_LOGOUT',

    /* PROFLE UPDATE */
    USER_PROFILE_UPDATE_REQUEST: 'USER_PROFILE_UPDATE_REQUEST',
    USER_PROFILE_UPDATE_SUCCESS: 'USER_PROFILE_UPDATE_SUCCESS',
    USER_PROFILE_UPDATE_FAILED: 'USER_PROFILE_UPDATE_FAILED',

}