export const productConstants = {
    // Products action types
    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAILED: 'PRODUCT_LIST_FAILED',

    // Product Detail action types
    SINGLE_PRODUCT_REQUEST: 'SINGLE_PRODUCT_REQUEST',
    SINGLE_PRODUCT_SUCCESS: 'SINGLE_PRODUCT_SUCCESS',
    SINGLE_PRODUCT_FAILED: 'SINGLE_PRODUCT_FAILED',
}